name = "PhotonPropagation"
uuid = "28d5a9e5-7176-4325-9f36-6543c975d45b"
authors = ["Christian Haack"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
